const commonSrc = "/images/home-page/blank.png";
const commonDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris finibus enim quis orci finibus imperdiet.";

export const baseData = [
  { href: "zaklady-principy/typografia", src: "/images/zaklady-principy-cards/Typografia.png", title: "Typografia", description: "Pravidlá pre použitie textových prvkov, typov a veľkostí písma.", alt: "Typografia: pravidlá pre textové prvky, typy a veľkosti písma" },
  { href: "zaklady-principy/farebna-paleta", src: "/images/zaklady-principy-cards/Farby.png", title: "Farby", description: "Prehľad farebných paletiet pre grafické používateľské rozhranie.", alt: "Farebná paleta: prehľad farebných paletiet pre GUI" },
  { href: "zaklady-principy/ikony", src: "/images/zaklady-principy-cards/Ikony.png", title: "Ikony", description: "Súbor vizuálnych symbolov používateľského rozhrania.", alt: "Ikony: súbor vizuálnych symbolov používateľského rozhrania" },
  { href: "zaklady-principy/tiene", src: "/images/zaklady-principy-cards/Tiene.png", title: "Tiene", description: "Typy tieňov a ich použitie na vizuálne rozlíšenie obsahu.", alt: "Tiene: typy tieňov a ich použitie na rozlíšenie obsahu" },
  { href: "zaklady-principy/medzery", src: "/images/zaklady-principy-cards/Medzery.png", title: "Medzery", description: "Medzery a ich rozmery.", alt: "Medzery: pravidlá a rozmery medzier" },
  { href: "zaklady-principy/grid", src: "/images/zaklady-principy-cards/Grid.png", title: "Grid", description: "Pravidlá rozloženia stránky do jedného alebo viacerých stĺpcov.", alt: "Grid: pravidlá rozloženia stránky do stĺpcov" }
];

export const componentsData = [
  { href: "komponenty/hlavicka", src: "/images/komponenty-cards/hlavicka-web-sidla.png", title: "Hlavička - webové sídla", description: "Hlavná navigácia webovej stránky", alt: "Hlavička: hlavná navigácia webovej stránky" },
  { href: "komponenty/hlavicka", src: "/images/komponenty-cards/hlavicka-web-aplikacie.png", title: "Hlavička - webové aplikácie", description: "Hlavička pre rozhrania, ktoré vyžadujú autentifikáciu používateľa.", alt: "Hlavička: rozhrania vyžadujúce autentifikáciu" },
  { href: "komponenty/pata", src: "/images/komponenty-cards/pata.png", title: "Päta", description: "Informácie o prevádzkovateľovi webovej stránky a textové odkazy.", alt: "Päta: informácie o prevádzkovateľovi a odkazy" },
  { href: "komponenty/akordeon", src: "/images/komponenty-cards/akordeon.png", title: "Akordeón", description: "Nástroj na zobrazenie alebo skrývanie prehľadu sekcií súvisiaceho obsahu.", alt: "Akordeón: zobrazenie alebo skrývanie sekcií" },
  { href: "komponenty/lista-spatnej-vazby", src: "/images/komponenty-cards/lista-spatnej-vazby.png", title: "Lišta spätnej väzby", description: "Slúži na návrhy a vyjadrenie spokojnosti s informáciami získanými na stránke.", alt: "Lišta spätnej väzby: návrhy a vyjadrenie spokojnosti" },
  { href: "/komponenty/text-input", src: "/images/komponenty-cards/textove-pole.png", title: "Textové pole", description: "Prvok, kam užívateľ zadáva textovú informáciu", alt: "Textové pole: zadanie textovej informácie" },
  { href: "/komponenty/text-input", src: "/images/komponenty-cards/viacriadkove-text-pole.png", title: "Viacriadkové textové pole", description: "Prvok, kam užívateľ zadáva textovú informáciu vo viacerých riadkoch", alt: "Viacriadkové textové pole: zadanie informácie vo viacerých riadkoch" },
  { href: "/komponenty/text-input", src: "/images/komponenty-cards/pole-pre-nahratie-suboru.png", title: "Pole pre nahratie súboru", description: "Nástroj umožňujúci používateľom nahrať súbory.", alt: "Pole pre nahratie súboru: nástroj na nahranie súborov" },
  { href: "/komponenty/radio-button", src: "/images/komponenty-cards/prepinacie-pole.png", title: "Prepínacie pole", description: "Formulárový prvok pre výber jednej z preddefinovaných možností.", alt: "Prepínacie pole: výber jednej z možností" },
  { href: "/komponenty/tlacidlo", src: "/images/komponenty-cards/tlacidlo-primarne.png", title: "Tlačidlo - Primárne", description: "Hlavné akčné prvky, ktoré majú najväčší vplyv na používateľskú interakciu.", alt: "Tlačidlo - Primárne: hlavné akčné prvky" },
  { href: "/komponenty/tlacidlo", src: "/images/komponenty-cards/tlacidlo-sekundarne.png", title: "Tlačidlo - Sekundárne", description: "Vedľajšie akčné prvky, ktoré môžu byť potrebné v určitých situáciách.", alt: "Tlačidlo - Sekundárne: vedľajšie akčné prvky" },
  { href: "/komponenty/tlacidlo", src: "/images/komponenty-cards/tlacidlo-textove.png", title: "Tlačidlo - Textové", description: "Nástroj na užívateľskú interakciu s najnižšou prioritou.", alt: "Tlačidlo - Textové: nástroj na interakciu s najnižšou prioritou" },
  { href: "/komponenty/informacna-lista", src: "/images/komponenty-cards/info-lista-upozornenie.png", title: "Inf.lišta - Upozornenie", description: "Výrazný prvok, upozornenie použivateľa o podstatných/nových informáciach", alt: "Inf.lišta - Upozornenie: upozornenie o podstatných informáciach" },
  { href: "/komponenty/informacna-lista", src: "/images/komponenty-cards/info-lista-oznamenie.png", title: "Inf.lišta - Oznámenie", description: "Prvok slúžiaci na zobrazenie permanentnej informácie pre používateľa.", alt: "Inf.lišta - Oznámenie: zobrazenie permanentnej informácie" },
  { href: "/komponenty/karticka", src: "/images/komponenty-cards/karticka.png", title: "Kartička", description: "Vizuálna reprezentácia obsahu článkov alebo podstránok.", alt: "Kartička: vizuálna reprezentácia článkov alebo podstránok" },
  { href: "/komponenty/checkbox", src: "/images/komponenty-cards/zaskrtavacie-pole.png", title: "Zaškrtávacie pole", description: "Interaktívny prvok, ktorý umožňuje používateľovi vybrať jednu alebo viacero položiek.", alt: "Zaškrtávacie pole: výber jednej alebo viacerých položiek" },
  { href: "/komponenty/dropdown", src: "/images/komponenty-cards/rozbalovaci-zoznam.png", title: "Rozbaľovací zoznam", description: "Interaktívny zoznam akcií alebo možností, ktoré je možné vybrať", alt: "Rozbaľovací zoznam: interaktívny zoznam akcií" },
  { href: "/komponenty/text-input", src: "/images/komponenty-cards/chyby-a-validacie.png", title: "Chyby a validácie", description: "Pravidlá ako zobrazovať chyby a validácie v elektronickom formulári.", alt: "Chyby a validácie: pravidlá zobrazovania chýb" },
  { href: "/komponenty/razcestnik", src: commonSrc, title: "Vertikálny rázcestník", description: "Navigačný prvok formou jednoduchej dlaždice usporiadanej vertikálne", alt: "Vertikálny rázcestník: navigačný prvok s vertikálnou dlaždicou" },
  { href: "/komponenty/razcestnik", src: commonSrc, title: "Horizontálny rázcestník", description: "Navigačný prvok formou jednoduchej dlaždice usporiadanej horizontálne", alt: "Horizontálny rázcestník: navigačný prvok s horizontálnou dlaždicou" },
  { href: "/komponenty/razcestnik", src: commonSrc, title: "Textový rázcestník", description: "Navigačný prvok formou jednoduchej dlaždice , zloženej z nadpisu, popisu a oddeľovacej čiary.", alt: "Textový rázcestník: navigačný prvok s nadpisom a popisom" }
];

export const whatIsData = [
  { href: "/co-je/uvod", src: "/images/co-je-cards/co-je-id-sk.png", title: "Úvod o dizajn manuále ID-SK", description: "ID-SK vznikol najmä za účelom zaistenia konzistentnosti dizajnu používateľských rozhraní elektronických služieb a webových sídiel slovenského e-Governmentu.", alt: "Úvod o dizajn manuále ID-SK: základné informácie" },
  { href: "/co-je/principy", src: "/images/co-je-cards/10-principov-idsk.png", title: "10 princípov ID-SK", description: "10 princípov tvorby elektronických služieb podľa IDSK. Dizajn služby začína identifikáciou potrieb používateľov...", alt: "Využitie ID-SK v praxi: príklady použitia" },
  { href: "/co-je/metodika", src: "/images/co-je-cards/metodika-ucd.png", title: "Metodika UCD", description: "Metodika user-centered dizajnu (UCD) zabezpečí zmysluplnosť a použiteľnosť služieb zo strany koncového používateľa - občana.", alt: "Plán vývoja: budúce smerovanie" },
  { href: "/co-je/navod-pre-dizajnerov", src: "/images/co-je-cards/navod-pre-dizajnerov.png", title: "Návod pre dizajnérov", description: "V dizajnérskom nástroji Figma nájdete knižnicu dizajnového systému ID-SK", alt: "Technické nastavenia a návody: inštrukcie a konfigurácia" },
  { href: "/co-je/navod-pre-vyvojarov", src: "/images/co-je-cards/navod-pre-vyvojarov.png", title: "Návody pre vývojárov", description: 'Ak budete chcieť vytvoriť elektronickú službu pomocou ID-SK, môžete využiť repozitár dostupný na GitHub-e.', alt: "História zmien: prehľad aktualizácií" },
];

export const homePageData = [
  { href: "/co-je", src: "/images/home-page/co-je-idsk.png", title: "Čo je ID-SK", description: "Jednotný dizajn manuál elektronických služieb Slovenska. „ID-SK“ je dizajnový systém + manuál na tvorbu elektronických služieb a webových sídiel štátu.", alt: "Čo je ID-SK: jednotný dizajn manuál" },
  { href: "/co-je/principy", src: "/images/home-page/10-principov.png", title: "10 princípov ID-SK", description: "1. princíp – princíp užitočnosti – začnite potrebami používateľov. Dizajn služby začína identifikáciou potrieb používateľov. Nevychádzajte z domnienok.", alt: "10 princípov ID-SK: princíp užitočnosti" },
  { href: "/co-je/metodika", src: "/images/home-page/metodika-a-usmernenia.png", title: "Metodika a usmernenia", description: "Elektronické služby štátu by mali byť pripravované metodikou User-Centered Design (UCD), aby sa zabezpečila zmysluplnosť a použiteľnosť služieb občanmi.", alt: "Metodika a usmernenia: User-Centered Design" },
  { href: "/zaklady-principy", src: "/images/home-page/zaklady-style-guide.png", title: "Základy (Style guide)", description: "Súbor štýlov používateľského rozhrania a štandardov dizajnu pre komponenty. Typografia, farebná paleta, ikony, tiene, medzery, stĺpce, použitie obrázkov, ...", alt: "Základy (Style guide): štýly a štandardy" },
  { href: "/komponenty", src: "/images/home-page/komponenty.png", title: "Komponenty", description: "Knižnica komponentov, ktoré sa používajú na tvorbu elektronických služieb a webových sídiel. Akordeón, Dátové polia, Hlavička, Päta, Tlačidlá, ...", alt: "Komponenty: knižnica komponentov" },
  { href: "/vzory", src: "/images/home-page/vzory-ux-patterns.png", title: "Vzory (UX patterns)", description: "Používanie a adaptácia návrhových vzorov: Adresy, Aktuality, Blok s rázcestníkom, Cookie banner, Článok, Dátum, Indikátor progresu, Meno, Priezvisko, Email...", alt: "Vzory (UX patterns): návrhové vzory" },
];